---
- name: Rename newly created host
  hosts: CombinedDB
  roles:
    - pnpsetup
  remote_user: ec2-user
  become_user: root
  become: yes
  vars:
     hostname: CombinedDB
     oraclesid: CTPNP
     domain: cte-prod.aws.gwl.com
     ipaddress: 10.146.55.81
